Code/base/urls.py
# SPDX-License-Identifier: BSD-3-Clause
"""
urls.py

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges, J. Luelsdorf <lsd@luetze.de>
"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include("lsd.urls")),
    path("admin/", admin.site.urls),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="lsd/login.html"),
        name="login",
    ),
    path(
        "logout/", auth_views.LogoutView.as_view(next_page="/software/"), name="logout"
    ),
    path("licenses/", include("licenses.urls")),
    path("products/", include("products.urls")),
    path("rest_api/", include("rest_api.urls")),
    path("software/", include("software.urls")),
    path("tools/", include("tools.urls")),
    path("va/", include("va.urls"))

]

Code/software/urls.py
#SPDX-License-Identifier: BSD-3-Clause
'''
urls.py

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, J. Luelsdorf <lsd@luetze.de>
'''
from django.urls import path
from software import views

urlpatterns = [
    path("", views.software_list, name="software-list"),
    path("<str:software_name>", views.software_details, name="software-detail"),
    path("<str:software_name>/change",
        views.software_details_change,
        name="software-detail-change",
    ),
    path(
        "<str:software_name>/latest",
        views.software_details_latest,
        name="software-datail-latest",
    ),
    path(
        "<str:software_name>/nightly",
        views.software_details_nightly,
        name="software-detail-nightly",
    ),
    path(
        "<str:software_name>/<str:software_version>",
        views.software_details_version,
        name="software-detail-version",
    ),
    path(
        "<str:software_name>/<str:software_version>/release",
        views.software_details_version_release,
        name="software-detail-version-release",
    ),
    path(
        "<str:software_name>/<str:software_version>/withdraw",
        views.software_details_version_withdraw,
        name="software-detail-version-withdraw",
    ),
    path(
        "<str:software_name>/<str:software_version>/addLicense",
        views.add_license_to_release,
        name="add_license_to_release",
    ),
]

Code/va/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(''                                     , views.va                    , name='lsd-va'                 ),
    path('latest'                               , views.va_details_latest     , name='lsd-va-latest'          ),
    path('latest/doc'                           , views.va_details_latest_doc , name='lsd-va-latest-doc'      ),
    path('latest/sw'                            , views.va_details_latest_sw  , name='lsd-va-latest-sw'       ),
    path('nightly'                              , views.va_details_nightly    , name='lsd-va-nightly'         ),
    path('nightly/doc'                          , views.va_details_nightly_doc, name='lsd-va-nightly-doc'     ),
    path('nightly/sw'                           , views.va_details_nightly_sw , name='lsd-va-nightly-sw'      ),
    path('<path:branch_type>'                    , views.va_branch             , name='lsd-va-branch-type'     ),
    path('<str:branch_type>/<str:branch_name>'  , views.va_branch_name        , name='lsd-va-branch-type-name'),
]

Code/software/models.py
#SPDX-License-Identifier: BSD-3-Clause
'''
models.py

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges, J. Luelsdorf <lsd@luetze.de>

'''
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Release(models.Model):
    """
    A Release represents Software which is developed by the Company.
    Every Release has different Users, which fill in different Roles.
    """
    STATUS_CODES = (
        ("d", "Draft"),
        ("r", "Released"),
        ("w", "Withdrawn"),
    )

    SIL_LEVEL = (
        (0, "Basic Integrity"),
        (1, "SIL1"),
        (2, "SIL2"),
    )

    SOFTWARE_TYPE = (
        ("i", "Internal"),
        ("e", "External"),
        ("t", "Third Party"),
    )

    title = models.CharField(max_length=100)
    version_string = models.TextField()
    version_major = models.IntegerField()
    version_minor = models.IntegerField()
    version_micro = models.IntegerField()
    version_build = models.IntegerField()
    version_commit = models.CharField(max_length=100)
    git_path = models.CharField(max_length=512)
    bin_path = models.CharField(max_length=512)
    doc_path_html = models.CharField(max_length=512)
    doc_path_pdf = models.CharField(max_length=512)
    date = models.DateTimeField(default=timezone.now)
    laste_edited_by = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="last_edit_user", null=True
    )
    status = models.CharField(max_length=1, choices=STATUS_CODES, default="d")
    sil_level = models.IntegerField(choices=SIL_LEVEL, default="0")
    developer = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="developer_user", null=True
    )
    tester = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="tester_user", null=True
    )
    verifier = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="verifier_user", null=True
    )
    process_version = models.ForeignKey(
        "self", on_delete=models.PROTECT, related_name="using_releases", null=True
    )
    software_type = models.CharField(max_length=1, choices=SOFTWARE_TYPE, default="i")
    responsible_user = models.ForeignKey(
        User,
        on_delete=models.PROTECT,
        related_name="responsible_user_release",
        null=True,
    )
    linked_tools = models.ManyToManyField("tools.Tool", related_name="releases")
    linked_licenses = models.ManyToManyField(
        "licenses.License", related_name="licenses", blank=True
    )
    linked_packages = models.ManyToManyField(
        "packages.Package", related_name="package", blank=True
    )

    def __str__(self):
        return str(self.title)


    def get_url_list(self):
        """
        ToDo delete this function or add Description.
        """
        return "/software/{}".format(self.title)

    def get_url_details(self):
        """
        ToDo delete this function or add Description.
        """
        return "/software/{}/{}".format(self.title, self.version_string)

Code/software/forms.py
#SPDX-License-Identifier: BSD-3-Clause
'''
forms.py

(C) Copyright 2020 Friedrich Luetze GmbH, J. Luelsdorf <lsd@luetze.de>
'''
from django import forms
from software.models import Release


class ReleaseAddLicenseForm(forms.ModelForm):
    """
    Form, used to add or change the License a software
    release uses.
    """
    class Meta:
        model = Release
        fields = ["linked_licenses"]

Code/software/views.py
#SPDX-License-Identifier: BSD-3-Clause

'''
views.py

(C) Copyright 2020 Friedrich Luetze GmbH, S. Hentges, J. Luelsdorf <lsd@luetze.de>
'''
from django.shortcuts import render, redirect
from django.http import HttpResponseForbidden
from django.contrib import messages
from django.db import IntegrityError
from software.models import Release
from software.forms import ReleaseAddLicenseForm


def software_list(request):
    """
    Renders a template with a list of every software.
    """
    release_list = []
    release_title_list = []
    for release in Release.objects.all():
        if release.title not in release_title_list:
            release_title_list.append(release.title)
            release_list.append(release)

    context = {"softwares": release_list}
    return render(request, "software/software_list.html", context)


def software_details(request, software_name):
    """
    Renders a template with a single software with a specific software_name
    """
    context = {
        "releases": Release.objects.order_by("-date").filter(title=software_name)
    }
    return render(request, "software/software_releases_details.html", context)


def software_details_change(request, software_name):
    """
    Loads a form to add a used license to the software.
    """
    if request.user.is_authenticated:
        if request.method == "POST":
            releases = Release.objects.order_by("-date").filter(title=software_name)
            for release in releases:

                if not license in release.linked_licenses.all():
                    release.linked_licenses.add(license)
                    release.save()
            return redirect("software-detail", software_name=software_name)
        form = ReleaseAddLicenseForm()
        return render(request, "software/releaseAddLicenseForm.html", {"form": form})
    return render(request, "lsd/unauthenticated_User_page.html")


def software_details_latest(request, software_name):
    """
    Displaies the latest software which was released.
    !Carefull, when a software hasn't the status r, the
    User won't be redirected.
    """
    context = {
        "release": Release.objects.order_by("-date").filter(
            title=software_name, status="r"
        )[0]
    }
    return render(request, "software/software_release_details.html", context)


def software_details_nightly(request, software_name):
    """
    Shows latest pushed Software.
    """
    context = {
        "release": Release.objects.order_by("-date").filter(title=software_name)[0]
    }
    return render(request, "software/software_release_details.html", context)


def software_details_version(request, software_name, software_version):
    """
    Renders a software with a specific name and version.
    """
    context = {
        "release": Release.objects.order_by("-date").filter(
            title=software_name, version_string=software_version
        )[0]
    }
    return render(request, "software/software_release_details.html", context)


def software_details_version_release(request, software_name, software_version):
    """
    Changes the release status of a specific software version to released.
    """
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    release = Release.objects.order_by("-date").filter(
        title=software_name, version_string=software_version
    )[0]
    release.status = "r"
    release.save()
    return redirect("/software/{}/{}".format(software_name, software_version))


def software_details_version_withdraw(request, software_name, software_version):
    """
    Changes the release status of a specific software version to withdrawn.
    """
    if not request.user.is_authenticated:
        return HttpResponseForbidden()

    release = Release.objects.order_by("-date").filter(
        title=software_name, version_string=software_version
    )[0]
    release.status = "w"
    release.save()
    return redirect("/software/{}/{}".format(software_name, software_version))


def add_license_to_release(request, software_name, software_version):
    """
    An authenticated User can choose an existing License and add it to a Software Release
    """
    if request.user.is_authenticated:

        if request.method == "POST":
            try:
                release = Release.objects.filter(
                    title=software_name, version_string=software_version
                )[0]
                linked_licenses = request.POST.dict()["linked_licenses"]
                release.linked_licenses.add(linked_licenses)
                messages.success(request, "License(s) added to Release")
                return redirect(
                    "software-detail-version",
                    software_name=software_name,
                    software_version=software_version,
                )
            except KeyError:
                form = ReleaseAddLicenseForm()
                messages.warning(request, "Please choose a license from the box.")
                return render(request, "software/releaseAddLicenseForm.html", {"form": form})
            except IntegrityError:
                form = ReleaseAddLicenseForm()
                messages.warning(request, "A license with that title already exists in Release.")
                return render(request, "software/releaseAddLicenseForm.html", {"form": form})

        elif request.method == "GET":
            form = ReleaseAddLicenseForm()
            return render(request, "software/releaseAddLicenseForm.html", {"form": form})

    return render(request, "lsd/unauthenticated_User_page.html")

Code/software/templates/software/releaseAddLicenseForm.html
<!--SPDX-License-Identifier: BSD-3-Clause-->
<!--
releaseAddLicenseForm.html

(C) Copyright 2020 Friedrich Luetze GmbH, J. Luelsdorf <lsd@luetze.de>

-->
{% extends "lsd/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Add a new License</legend>
        {{ form|crispy }}
      </fieldset>
      <div class="form-group">
        <button class="btn btn-outline-info" type="submit">Add License</button>
      </div>
    </form>
  </div>
{% endblock content %}

Code/software/templates/software/software_list.html
<!--SPDX-License-Identifier: BSD-3-Clause-->
<!--
software_list.html

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges, J. Luelsdorf <lsd@luetze.de>

-->
{% extends "lsd/base.html" %}
{% block content %}
    {% for software in softwares %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'software-detail' software %}">{{ software }}</a>
            </div>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

Code/software/templates/software/software_release_details.html
<!--SPDX-License-Identifier: BSD-3-Clause-->
<!--
software_release_details.html

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges, J. Luelsdorf <lsd@luetze.de>

-->
{% extends "lsd/base.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <h2>{{ release.title }}</h2>
      </div>
      <table class="table table-striped">
        <tr>
          <th scope="row">Version:</th>
          <td>{{ release.version_string }}</td>
        </tr>
        <tr>
          <th scope="row">Date:</th>
          <td>{{ release.date|date:"Y-m-d" }} {{ release.date|time:"H:i" }}</td>
        </tr>
        <tr>
          <th scope="row">Software:</th>
          <td><a href="{% url 'lsd-home' %}{{ release.bin_path }}">download Software</a></td>
        </tr>
        <tr>
          <th scope="row">Documentation:</th>
          <td><a href="{% url 'lsd-home' %}{{ release.doc_path_html }}">show doc</a></td>
        </tr>
        <tr>
          <th scope="row">Status:</th>
          <td>{{ release.get_status_display }}</td>
        </tr>
        <tr>
          <th scope="row">Responsible:</th>
          <td>{{ release.responsible_user }}</td>
        </tr>
        <tr>
          <th scope="row">SIL Level:</th>
          <td>{{ release.get_sil_level_display }}</td>
        </tr>
        <tr>
          <th scope="row">Developer:</th>
          <td>{{ release.developer }}</td>
        </tr>
        <tr>
          <th scope="row">Tester:</th>
          <td>{{ release.tester }}</td>
        </tr>
        <tr>
          <th scope="row">Verifier:</th>
          <td>{{ release.verifier }}</td>
        </tr>
        <tr>
          <th scope="row">Software Type:</th>
          <td>{{ release.get_software_type_display }}</td>
        </tr>
        <tr>
          <th scope="row">Process version:</th>
          <td>
            {{ release.process_version.version_string }}
          </td>
        </tr>
        <tr>
          <th scope="row">Tools Used:</th>
          <td>
            {% for tool in release.linked_tools.all %}
              {{ tool.title }}, Version: {{ tool.version }} </br>
            {% endfor %}
          </td>
        </tr>
        <tr>
          <th scope="row">Products:</th>
          <td>
            {% for product in release.releases.all %}
              {{ product.title }}, Version: {{ product.article_number}} </br>
            {% endfor %}
          </td>
        </tr>
        <tr>
          <th scope="row">Used licenses:</th>
          <td>
            {% for license in release.linked_licenses.all %}
              <a href="{% url 'license-details' license.title %}">{{license.title}}</a></br>
            {% endfor %}
            </br>
              <a href="{% url 'add_license_to_release' release.title release.version_string %}" >Add a new License</a>
          </td>
        </tr>
        <tr>
        <table class="table table-striped">
          <th scope ="row">Used Packages:</th>

          <tr>
          <td><b>Packagename:</b></td>
          <td><b>Packageversion:</b></td>
          <td><b>Used License of Package: </b></td>
          <td><b>Type of Package: </b></td>
          </tr>
          {%for package in release.linked_packages.all %}
          <tr>
          <td>
            {{package.package_name}}
          </td>
          <td>
            {{package.package_version}}
          </td>
          <td>
            <a href="{%url 'license-details' package.license_used.title%}">{{package.license_used}}</a>
          </td>
          <td>
            {%if package.usage == 'd' %}
            dynamic
            {%endif%}
            {%if package.usage == 's' %}
            static
            {%endif%}
            {%if package.usage == 'r' %}
            rootfs
            {%endif%}
            {%if package.usage == 'u' %}
            unkown
            {%endif%}
          </td>
          </tr>
          {% endfor %}
        </tr>
      </table>
      </table>
      {% if user.is_authenticated %}
        {% if release.status == 'd' %}
          <a href="{{ release.version_string }}/release">
            <button type="button" class="btn btn-primary">Release</button>
          </a>
        {% elif release.status == "r" %}
          <a href="{{ release.version_string }}/withdraw">
            <button type="button" class="btn btn-primary">Withdraw</button>
          </a>
        {% endif %}
      {% endif %}
    </div>
  </article>
{% endblock content %}

Code/software/templates/software/software_releases_details.html
<!--SPDX-License-Identifier: BSD-3-Clause-->
<!--
software_releases_details.html

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges, J. Luelsdorf <lsd@luetze.de>

-->
{% extends "lsd/base.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
  {% for release in releases %}
      <div class="article-metadata">
        <h2>{{ release.title }}</h2>
      </div>
      <table class="table table-striped">
        <tr>
          <th scope="row">Version:</th>
          <td><a href="{{ release.get_url_details }}">{{ release.version_string }}</a></td>
        </tr>
        <tr>
          <th scope="row">Date:</th>
          <td>{{ release.date|date:"Y-m-d" }} {{ release.date|time:"H:i" }}</td>
        </tr>
        <tr>
          <th scope="row">Software:</th>
          <td><a href="{% url 'lsd-home' %}{{ release.bin_path }}">download Software</a></td>
        </tr>
        <tr>
          <th scope="row">Documentation:</th>
          <td><a href="{% url 'lsd-home' %}{{ release.doc_path_html }}">show doc</a></td>
        </tr>
        <tr>
          <th scope="row">Status:</th>
          <td>{{ release.get_status_display }}</td>
        </tr>
        <tr>
          <th scope="row">Responsible:</th>
          <td>{{ release.responsible_user }}</td>
        </tr>
        <tr>
          <th scope="row">SIL Level:</th>
          <td>{{ release.get_sil_level_display }}</td>
        </tr>
        <tr>
          <th scope="row">Developer:</th>
          <td>{{ release.developer }}</td>
        </tr>
        <tr>
          <th scope="row">Tester:</th>
          <td>{{ release.tester }}</td>
        </tr>
        <tr>
          <th scope="row">Verifier:</th>
          <td>{{ release.verifier }}</td>
        </tr>
        <tr>
          <th scope="row">Software Type:</th>
          <td>{{ release.get_software_type_display }}</td>
        </tr>
        <tr>
          <th scope="row">Process version:</th>
          <td>
            {{ release.process_version.version_string }}
          </td>
        </tr>
        <tr>
          <th scope="row">Tools Used:</th>
          <td>
            {% for tool in release.linked_tools.all %}
              {{ tool.title }}, Version: {{ tool.version }} </br>
            {% endfor %}
          </td>
        </tr>
        <tr>
          <th scope="row">Products:</th>
          <td>
            {% for product in release.releases.all %}
              {{ product.title }}, Version: {{ product.article_number}} </br>
            {% endfor %}
          </td>
        </tr>
      </table>
    {% endfor %}
    </div>
  </article>
{% endblock content %}