Code/base/urls.py
# SPDX-License-Identifier: BSD-3-Clause
"""
urls.py

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges, J. Luelsdorf <lsd@luetze.de>
"""
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("", include("lsd.urls")),
    path("admin/", admin.site.urls),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="lsd/login.html"),
        name="login",
    ),
    path(
        "logout/", auth_views.LogoutView.as_view(next_page="/software/"), name="logout"
    ),
    path("licenses/", include("licenses.urls")),
    path("products/", include("products.urls")),
    path("rest_api/", include("rest_api.urls")),
    path("software/", include("software.urls")),
    path("tools/", include("tools.urls")),
    path("va/", include("va.urls"))

]

Code/tools/urls.py
#SPDX-License-Identifier: BSD-3-Clause
'''
urls.py

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges <lsd@luetze.de>
'''
from django.urls import path
from tools import views

urlpatterns = [
    path("", views.tools_list, name="tools-list"),
    path("<str:tool_name>", views.tool_version_list, name="tool-version-list"),
    path("<str:tool_name>/<str:tool_version>", views.tool_details, name="tool-details"),
]

Code/va/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path(''                                     , views.va                    , name='lsd-va'                 ),
    path('latest'                               , views.va_details_latest     , name='lsd-va-latest'          ),
    path('latest/doc'                           , views.va_details_latest_doc , name='lsd-va-latest-doc'      ),
    path('latest/sw'                            , views.va_details_latest_sw  , name='lsd-va-latest-sw'       ),
    path('nightly'                              , views.va_details_nightly    , name='lsd-va-nightly'         ),
    path('nightly/doc'                          , views.va_details_nightly_doc, name='lsd-va-nightly-doc'     ),
    path('nightly/sw'                           , views.va_details_nightly_sw , name='lsd-va-nightly-sw'      ),
    path('<path:branch_type>'                    , views.va_branch             , name='lsd-va-branch-type'     ),
    path('<str:branch_type>/<str:branch_name>'  , views.va_branch_name        , name='lsd-va-branch-type-name'),
]

Code/tools/models.py
#SPDX-License-Identifier: BSD-3-Clause
'''
models.py

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges <lsd@luetze.de>
'''
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone


class Tool(models.Model):
    """
    The Tool class represents the Tools used by the LSD.
    This can be variyng.
    """
    USAGE_STATUS = (
        ("a", "Approved"),
        ("l", "locked"),
    )

    SIL_LEVEL = (
        (0, "Basic Integrity"),
        (1, "SIL1"),
        (2, "SIL2"),
    )

    CLASSIFICATION = (
        (1, "T1"),
        (2, "T2"),
        (3, "T3"),
    )

    title = models.CharField(max_length=100)
    description = models.TextField()
    version = models.CharField(max_length=100)
    usage_status = models.CharField(max_length=1, choices=USAGE_STATUS, default="l")
    release_status = models.IntegerField(choices=SIL_LEVEL, default=0)
    responsible_user = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="responsible_user_tool", null=True
    )
    proxy_user = models.ForeignKey(
        User, on_delete=models.PROTECT, related_name="proxy_user", null=True
    )
    comment = models.TextField()
    system_requirements = models.TextField()
    license_model = models.TextField()
    license_host_path = models.CharField(max_length=512)
    classification = models.IntegerField(choices=CLASSIFICATION, null=True)
    specification_path = models.CharField(max_length=512)
    manual_path = models.CharField(max_length=512)
    proof_of_compliance_path = models.CharField(max_length=512)
    characterization_path = models.CharField(max_length=512)
    date_posted = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.title)

Code/tools/views.py
#SPDX-License-Identifier: BSD-3-Clause

'''
views.py

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges <lsd@luetze.de>
'''
from django.shortcuts import render
from tools.models import Tool


def tools_list(request):
    """
    Renders a list of used tools.
    """
    tools_temp_list = []
    for tool in Tool.objects.all():
        if tool.title not in tools_temp_list:
            tools_temp_list.append(tool.title)

    context = {"tools": tools_temp_list}
    return render(request, "tools/tools_list.html", context)


def tool_version_list(request, tool_name):
    """
    Renders a list of used tools with a specific name.
    """
    tools_temp_list = Tool.objects.order_by("-date_posted").filter(title=tool_name)
    context = {"tools": tools_temp_list}
    return render(request, "tools/tool_version_list.html", context)


def tool_details(request, tool_name, tool_version):
    """
    Renders a single tool, choosen through tool name and version number.
    """
    context = {
        "tool": Tool.objects.order_by("-date_posted").filter(
            title=tool_name, version=tool_version
        )[0]
    }
    return render(request, "tools/tool_details.html", context)

Code/tools/templates/tools/tool_details.html
<!--SPDX-License-Identifier: BSD-3-Clause-->
<!--
tool_details.html

(C) Copyright 2020 Friedrich Luetze GmbH, S. Hentges <lsd@luetze.de>
-->
{% extends "lsd/base.html" %}
{% block content %}
  <article class="media content-section">
    <div class="media-body">
      <div class="article-metadata">
        <h2>{{ tool.title }}</h2>
      </div>
      <table class="table table-striped">
        <tr>
          <th scope="row">Description:</th>
          <td>{{ tool.description }}</td>
        </tr>
        <tr>
          <th scope="row">Version:</th>
          <td>{{ tool.version }}</td>
        </tr>
        <tr>
          <th scope="row">Usage Status:</th>
          <td>
              {% if tool.usage_status == 'l' %}
              <p style="color:#FF0000">{{ tool.get_usage_status_display }}</p>
              {% elif tool.usage_status == 'a' %}
              <p style="color:#00FF00">{{ tool.get_usage_status_display }}</p>
              {% endif %}
          </td>
        </tr>
        <tr>
          <th scope="row">Release Status:</th>
          <td>{{ tool.get_release_status_display }}</td>
        </tr>
        <tr>
          <th scope="row">Classification:</th>
          <td>{{ tool.get_classification_display }}</td>
        </tr>
        <tr>
          <th scope="row">Responsible:</th>
          <td>{{ tool.responsible_user }}</td>
        </tr>
        <tr>
          <th scope="row">Proxy:</th>
          <td>{{ tool.proxy_user }}</td>
        </tr>
        <tr>
          <th scope="row">Comment:</th>
          <td>{{ tool.comment }}</td>
        </tr>
        <tr>
          <th scope="row">System Requirements:</th>
          <td>{{ tool.system_requirements }}</td>
        </tr>
        <tr>
          <th scope="row">License Model:</th>
          <td>{{ tool.license_model }}</td>
        </tr>
        <tr>
          <th scope="row">License Host:</th>
          <td>{{ tool.license_host_path }}</td>
        </tr>
        <tr>
          <th scope="row">Specification:</th>
          <td>{{ tool.specification_path }}</td>
        </tr>
        <tr>
          <th scope="row">Manual:</th>
          <td>{{ tool.manual_path }}</td>
        </tr>
        <tr>
          <th scope="row">Proof Of Compliance:</th>
          <td>{{ tool.proof_of_compliance_path }}</td>
        </tr>
        <tr>
          <th scope="row">Characterization:</th>
          <td>{{ tool.characterization_path }}</td>
        </tr>
        <tr>
          <th scope="row">Used For Release:</th>	
            <td>
              {% for release in tool.releases.all %}
                {{ release.title }}, Version: {{ release.version_string }} </br>
              {% endfor %}
            </td>
        </tr>
        <tr>
          <th scope="row">Date:</th>
          <td>{{ tool.date_posted|date:"Y-m-d" }} {{ tool.date_posted|time:"H:i" }}</td>
        </tr>
      </table>
    </div>
  </article>
{% endblock content %}

Code/tools/templates/tools/tool_version_list.html
<!--SPDX-License-Identifier: BSD-3-Clause-->
<!--
tool_version_list.html

(C) Copyright 2020 Friedrich Luetze GmbH, S. Hentges, J. Luelsdorf <lsd@luetze.de>
-->
{% extends "lsd/base.html" %}
{% block content %}
    {% for tool in tools %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{% url 'tool-details' tool tool.version %}">{{ tool }}</a>
              <small class="text-muted">{{ tool.date_posted|date:"Y-m-d" }} {{ tool.date_posted|time:"H:i" }}</small>
            </div>
            <p>Version: {{ tool.version }} </p> 
            <p>Classification: {{tool.get_classification_display}}</p>
            <p>SIL-Level: {{tool.get_release_status_display}}</p>
            {% if tool.usage_status == 'l' %}
              <p align="right" style="color:#FF0000">Status: {{ tool.get_usage_status_display }}</p>
            {% elif tool.usage_status == 'a' %}
              <p align="right" style="color:#00FF00">Status: {{ tool.get_usage_status_display }}</p>
            {% endif %}
          </div>
        </article>
    {% endfor %}
{% endblock content %}

Code/tools/templates/tools/tools_list.html
<!--SPDX-License-Identifier: BSD-3-Clause-->
<!--
tools_list.html

(C) Copyright 2020 Friedrich Luetze GmbH, S. Strobel, S. Hentges, J. Luelsdorf <lsd@luetze.de>

-->
{% extends "lsd/base.html" %}
{% block content %}
    {% for tool in tools %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{%url tool-version-list %}">{{ tool }}</a>
          </div>
        </article>
    {% endfor %}
{% endblock content %}